services:
  - type: web
    name: qtc-analyzer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn qt_dash_app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
